// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type MstPortfolio struct {
	ID              string `json:"id"`
	Title           string `json:"title"`
	Description     string `json:"description"`
	Backendstack    string `json:"backendstack"`
	Frontendstack   string `json:"frontendstack"`
	Databasestack   string `json:"databasestack"`
	Deploymentstack string `json:"deploymentstack"`
	Createdat       string `json:"createdat"`
	Createdby       string `json:"createdby"`
	Updatedat       string `json:"updatedat"`
	Updatedby       string `json:"updatedby"`
}

type Mutation struct {
}

type NewMstPortfolio struct {
	ID              string `json:"id"`
	Title           string `json:"title"`
	Description     string `json:"description"`
	Backendstack    string `json:"backendstack"`
	Frontendstack   string `json:"frontendstack"`
	Databasestack   string `json:"databasestack"`
	Deploymentstack string `json:"deploymentstack"`
	Createdat       string `json:"createdat"`
	Createdby       string `json:"createdby"`
	Updatedat       string `json:"updatedat"`
	Updatedby       string `json:"updatedby"`
}

type Query struct {
}
