package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"
	"fmt"
	"sadewa-portfolio-svc/config"
	"sadewa-portfolio-svc/graph/model"
)

// Fetch all mst_portfolios
func (r *queryResolver) MstPortfolios(ctx context.Context) ([]*model.MstPortfolio, error) {
	var mstportfolios []model.MstPortfolio

	// Use `config.DB` for database queries
	if err := config.DB.Find(&mstportfolios).Error; err != nil {
		return nil, err
	}

	// Convert database models to GraphQL models
	var result []*model.MstPortfolio
	for _, mp := range mstportfolios {
		result = append(result, &model.MstPortfolio{
			ID:              fmt.Sprintf("%d", mp.ID),
			Title:           mp.Title,
			Description:     mp.Description,
			BackendStack:    mp.BackendStack,
			FrontendStack:   mp.FrontendStack,
			DatabaseStack:   mp.DatabaseStack,
			DeploymentStack: mp.DeploymentStack,
			CreatedAt:       mp.CreatedAt,
			CreatedBy:       mp.CreatedBy,
			UpdatedAt:       mp.UpdatedAt,
			UpdatedBy:       mp.UpdatedBy,
		})
	}

	return result, nil
}

// MstPortfolio is the resolver for the mstPortfolio field.
func (r *queryResolver) MstPortfolio(ctx context.Context, id string) (*model.MstPortfolio, error) {
	panic(fmt.Errorf("not implemented: MstPortfolio - mstPortfolio"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
<<<<<<< HEAD

<<<<<<< HEAD
=======
// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	panic(fmt.Errorf("not implemented: Todos - todos"))
}
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }
type mutationResolver struct{ *Resolver }
*/
>>>>>>> feature/db-integration/init
=======
>>>>>>> 4fd5918 (still error db integration)
