package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"
	"fmt"
	"sadewa-portfolio-svc/graph/model"
)

// CreateMstPortfolio is the resolver for the createMstPortfolio field.
func (r *mutationResolver) CreateMstPortfolio(ctx context.Context, input model.NewMstPortfolio) (*model.MstPortfolio, error) {
	panic(fmt.Errorf("not implemented: CreateMstPortfolio - createMstPortfolio"))
}

// Mstportfolio is the resolver for the mstportfolio field.
func (r *queryResolver) Mstportfolio(ctx context.Context) ([]*model.MstPortfolio, error) {
	panic(fmt.Errorf("not implemented: Mstportfolio - mstportfolio"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
