package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"
	"fmt"
	"sadewa-portfolio-svc/graph/model"
)

// CreatePortfolio is the resolver for the createPortfolio field.
func (r *mutationResolver) CreatePortfolio(ctx context.Context, input model.PortfolioInput) (*model.Portfolio, error) {
	panic(fmt.Errorf("not implemented: CreatePortfolio - createPortfolio"))
}

// UpdatePortfolio is the resolver for the updatePortfolio field.
func (r *mutationResolver) UpdatePortfolio(ctx context.Context, id string, input model.PortfolioInput) (*model.Portfolio, error) {
	panic(fmt.Errorf("not implemented: UpdatePortfolio - updatePortfolio"))
}

// DeletePortfolio is the resolver for the deletePortfolio field.
func (r *mutationResolver) DeletePortfolio(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeletePortfolio - deletePortfolio"))
}

// Portfolios is the resolver for the portfolios field.
func (r *queryResolver) Portfolios(ctx context.Context) ([]*model.Portfolio, error) {
	panic(fmt.Errorf("not implemented: Portfolios - portfolios"))
}

// Portfolio is the resolver for the portfolio field.
func (r *queryResolver) Portfolio(ctx context.Context, id string) (*model.Portfolio, error) {
	panic(fmt.Errorf("not implemented: Portfolio - portfolio"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	panic(fmt.Errorf("not implemented: Todos - todos"))
}
*/
