package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"
	"fmt"
	"sadewa-portfolio-svc/graph/model"
)

// CreatePortfolio is the resolver for the createPortfolio field.
func (r *mutationResolver) CreatePortfolio(ctx context.Context, input model.PortfolioInput) (*model.Portfolio, error) {
	panic(fmt.Errorf("not implemented: CreatePortfolio - revised "))
}

// UpdatePortfolio is the resolver for the updatePortfolio field.
func (r *mutationResolver) UpdatePortfolio(ctx context.Context, id string, input model.PortfolioInput) (*model.Portfolio, error) {
	panic(fmt.Errorf("not implemented: UpdatePortfolio - updatePortfolio"))
}

// DeletePortfolio is the resolver for the deletePortfolio field.
func (r *mutationResolver) DeletePortfolio(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeletePortfolio - deletePortfolio"))
}

// Portfolios is the resolver for the portfolios field.
func (r *queryResolver) Portfolios(ctx context.Context) ([]*model.Portfolio, error) {
	panic(fmt.Errorf("not implemented: Portfolios - portfolios"))
}

// Portfolio is the resolver for the portfolio field.
func (r *queryResolver) Portfolio(ctx context.Context, id string) (*model.Portfolio, error) {
	panic(fmt.Errorf("not implemented: Portfolio - portfolio"))
}
