// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Experience struct {
	ID            string  `json:"id"`
	JobTitle      string  `json:"jobTitle"`
	JobStartDate  Time    `json:"jobStartDate"`
	JobFinishDate Time    `json:"jobFinishDate"`
	CreatedAt     Time    `json:"createdAt"`
	CreatedBy     *string `json:"createdBy,omitempty"`
	UpdatedAt     *Time   `json:"updatedAt,omitempty"`
	UpdatedBy     *string `json:"updatedBy,omitempty"`
	IsActive      bool    `json:"isActive"`
}

type ExperienceInput struct {
	JobTitle      string  `json:"jobTitle"`
	JobStartDate  Time    `json:"jobStartDate"`
	JobFinishDate Time    `json:"jobFinishDate"`
	CreatedAt     Time    `json:"createdAt"`
	CreatedBy     *string `json:"createdBy,omitempty"`
	IsActive      bool    `json:"isActive"`
}

type ExperienceMutation struct {
	CreateExperience *Experience `json:"createExperience"`
	UpdateExperience *Experience `json:"updateExperience"`
	DeleteExperience bool        `json:"deleteExperience"`
}

type ExperienceQuery struct {
	Experiences []*Experience `json:"experiences"`
	Experience  *Experience   `json:"experience,omitempty"`
}

type Portfolio struct {
	ID              string  `json:"id"`
	Title           string  `json:"title"`
	Description     *string `json:"description,omitempty"`
	BackendStack    *string `json:"backendStack,omitempty"`
	FrontendStack   *string `json:"frontendStack,omitempty"`
	DatabaseStack   *string `json:"databaseStack,omitempty"`
	DeploymentStack *string `json:"deploymentStack,omitempty"`
	CreatedAt       Time    `json:"createdAt"`
	CreatedBy       *string `json:"createdBy,omitempty"`
	UpdatedAt       *Time   `json:"updatedAt,omitempty"`
	UpdatedBy       *string `json:"updatedBy,omitempty"`
	IsActive        bool    `json:"isActive"`
}

type PortfolioInput struct {
	Title           string  `json:"title"`
	Description     *string `json:"description,omitempty"`
	BackendStack    *string `json:"backendStack,omitempty"`
	FrontendStack   *string `json:"frontendStack,omitempty"`
	DatabaseStack   *string `json:"databaseStack,omitempty"`
	DeploymentStack *string `json:"deploymentStack,omitempty"`
	CreatedBy       *string `json:"createdBy,omitempty"`
	UpdatedBy       *string `json:"updatedBy,omitempty"`
	IsActive        bool    `json:"isActive"`
}

type PortfolioMutation struct {
	CreatePortfolio *Portfolio `json:"createPortfolio"`
	UpdatePortfolio *Portfolio `json:"updatePortfolio"`
	DeletePortfolio bool       `json:"deletePortfolio"`
}

type PortfolioQuery struct {
	Portfolios []*Portfolio `json:"portfolios"`
	Portfolio  *Portfolio   `json:"portfolio,omitempty"`
}

type Query struct {
}
