// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type MstPortfolio struct {
	ID              string `json:"id"`
	Title           string `json:"title"`
	Description     string `json:"description"`
	BackendStack    string `json:"backend_stack"`
	FrontendStack   string `json:"frontend_stack"`
	DatabaseStack   string `json:"database_stack"`
	DeploymentStack string `json:"deployment_stack"`
	CreatedAt       string `json:"created_at"`
	CreatedBy       string `json:"created_by"`
	UpdatedAt       string `json:"updated_at"`
	UpdatedBy       string `json:"updated_by"`
}

type Query struct {
}
